return {
  "mason-org/mason.nvim",
  opts = {
    registries = {
      "github:Crashdummyy/mason-registry",
      "github:mason-org/mason-registry",
    },
    ensure_installed = {
      "roslyn",
      "netcoredbg",
      "csharpier",
      "lemminx",
      "powershell-editor-services",
      "html-lsp",
      "css-lsp",
      "json-lsp",
      "typescript-language-server",
      "vtsls",
      "emmet-language-server",
      "eslint-lsp",
      "prettier",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "yaml-language-server",
      "bash-language-server",
      "black",
      "tree-sitter-cli",
      "marksman",
      "lua-language-server",
      "markdownlint-cli2",
    },
  },
}
